CREATE TABLE COMMENT (
u_id BIGINT NOT NULL,
req_id BIGINT NOT NULL,
message VARCHAR(1024) NOT NULL,
create_date DATETIME DEFAULT CURRENT_TIMESTAMP() NOT NULL,
delete_date DATETIME NOT NULL,
is_delete BOOLEAN NOT NULL,
FOREIGN KEY(u_id) REFERENCES USER(u_id),
FOREIGN KEY(req_id) REFERENCES REQUEST(req_id)
) DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;