CREATE TABLE DELIVERY (
u_id BIGINT NOT NULL,
req_id BIGINT NOT NULL,
receive_name VARCHAR(20) NOT NULL,
parcel_num VARCHAR(20) NOT NULL,
address VARCHAR(20) NOT NULL,
detail_address VARCHAR(20) NOT NULL, 
FOREIGN KEY(u_id) REFERENCES USER(u_id),
FOREIGN KEY(req_id) REFERENCES REQUEST(req_id)
);