CREATE TABLE DIRECT (
u_id BIGINT NOT NULL,
req_id BIGINT NOT NULL,
loc VARCHAR(20) NOT NULL,
city VARCHAR(20) NOT NULL,
detail_address VARCHAR(20) NOT NULL, 
FOREIGN KEY(u_id) REFERENCES USER(u_id),
FOREIGN KEY(req_id) REFERENCES REQUEST(req_id)
);