CREATE TABLE PRODUCT_IMG (
u_id BIGINT NOT NULL,
req_id BIGINT NOT NULL,
image1 VARCHAR(20) NOT NULL,
image2 VARCHAR(20) NOT NULL,
image3 VARCHAR(20) NOT NULL,
image4 VARCHAR(20) NOT NULL,
FOREIGN KEY(u_id) REFERENCES USER(u_id),
FOREIGN KEY(req_id) REFERENCES REQUEST(req_id)
) DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;