CREATE TABLE REQUEST (
u_id BIGINT NOT NULL,
req_id BIGINT AUTO_INCREMENT, 
req_date DATETIME DEFAULT CURRENT_TIMESTAMP() NOT NULL,
req_expired DATE NOT NULL,
req_status VARCHAR(20) NOT NULL,
is_cancel BOOLEAN DEFAULT FALSE,
is_delivery BOOLEAN DEFAULT FALSE,
PRIMARY KEY(req_id),
FOREIGN KEY(u_id) REFERENCES USER(u_id)
);